const mockBooks = [
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classic",
    isbn: "978-0061120084",
    publisher: "Harper Perennial Modern Classics",
    year: 1960,
    copies: 10,
  },
  {
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    isbn: "978-0451524935",
    publisher: "Signet Classic",
    year: 1949,
    copies: 8,
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    isbn: "978-0590353427",
    publisher: "Bloomsbury",
    year: 1997,
    copies: 15,
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    isbn: "978-0743273565",
    publisher: "Scribner",
    year: 1925,
    copies: 12,
  },
  {
    title: "To the Lighthouse",
    author: "Virginia Woolf",
    genre: "Modernist",
    isbn: "978-0156907392",
    publisher: "Mariner Books",
    year: 1927,
    copies: 6,
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Literary Fiction",
    isbn: "978-0316769488",
    publisher: "Little, Brown and Company",
    year: 1951,
    copies: 9,
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    isbn: "978-0060850524",
    publisher: "Harper Perennial Modern Classics",
    year: 1932,
    copies: 7,
  },
  {
    title: "Moby-Dick",
    author: "Herman Melville",
    genre: "Adventure",
    isbn: "978-1542095624",
    publisher: "Classic Books Library",
    year: 1851,
    copies: 11,
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    isbn: "978-0141439518",
    publisher: "Penguin Classics",
    year: 1813,
    copies: 14,
  },
  {
    title: "Lord of the Flies",
    author: "William Golding",
    genre: "Dystopian",
    isbn: "978-0140283334",
    publisher: "Penguin Books",
    year: 1954,
    copies: 8,
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    isbn: "978-0547928227",
    publisher: "Houghton Mifflin Harcourt",
    year: 1937,
    copies: 13,
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    genre: "Psychological Fiction",
    isbn: "978-0143058146",
    publisher: "Penguin Books",
    year: 1866,
    copies: 10,
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    genre: "Gothic Fiction",
    isbn: "978-1503290295",
    publisher: "CreateSpace Independent Publishing Platform",
    year: 1890,
    copies: 6,
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    genre: "Gothic Fiction",
    isbn: "978-0486282114",
    publisher: "Dover Publications",
    year: 1818,
    copies: 9,
  },
  {
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    genre: "Social Fiction",
    isbn: "978-0143039433",
    publisher: "Penguin Books",
    year: 1939,
    copies: 11,
  },
];

export default mockBooks;
